name: Rust

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/onsen-tabi-github-actions-runner

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run coverage
        run: |
          cargo install cargo-llvm-cov
          rustup component add llvm-tools-preview
          cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: konabe/onsen_tabi
          files: lcov.info
          fail_ci_if_error: true

  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write
      contents: read
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: konabe/onsen_tabi:latest
      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Start
        run: aws autoscaling start-instance-refresh --auto-scaling-group-name onsen-tabi-web-auto-scaling
